version: '3.8'

services:
  anvil-app:
    build: .
    container_name: anvil_app_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: uvicorn anvil_api.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    container_name: anvil_worker_dev
    command: celery -A anvil_api.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  db:
    image: postgres:15
    container_name: anvil_db_dev
    environment:
      - POSTGRES_USER=anvil
      - POSTGRES_PASSWORD=anvil
      - POSTGRES_DB=anvil_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: anvil_redis_dev

volumes:
  postgres_data:
